name: Vividus Workflow

env:
  RELEASE_VERSION: 0.3.0

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '* 2 * * 6'

jobs:
  saucelabs-upload-by-schedule:
    if: github.event.schedule
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        run: |
          echo 1
  
  android-ci:
    if: github.event.push || github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Test 2
        run: |
          echo 2

  ios-ci:
    if: github.event.push || github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Test 2
        run: |
          echo 2
  
  saucelabs-upload:
    if: github.ref == 'refs/heads/master' && !github.event.schedule
    needs: [ android-ci, ios-ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Test 3
        run: |
          echo 3

  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo "Here"
          echo ${{ github.event.push }}
          echo ${{ github.event.pull_request }}
